### ISSUE TITLE
[Suggestion] Support for multiple models to exist

### ISSUE THREAD

**Issue by SimonRosengren** [ChetanXpro/nodejs-whisper#97] opened 2024-07-24 13:47 UTC
I've noticed that there is a check for any model existing as part of the autoDownload. However, it only checks if there are ``` > 0``` models rather than checking if the autoDownloadModelName already exists. 

```JS
if (existingModels.length > 0) {
	if (verbose) {
		console.log('[Nodejs-whisper] Models already exist. Skipping download.')
	}
	return 'Models already exist. Skipping download.'
}
```

It this by design or is it a bug? My suggestion would be to allow more than one model existing.

**Comment by SimonRosengren** [comment] 2024-07-24 14:27
I added a Pull Request for this as well in case you'd be interested

**Comment by ChetanXpro** [comment] 2024-07-30 12:18
@SimonRosengren Thanks for pointing out this issue. Yeah, initially it was by design, but I completely agree with you. I will review the PR soon.

**Comment by ChetanXpro** [comment] 2024-09-03 16:58
@SimonRosengren Merged the PR

**Closed by ChetanXpro** 2024-09-03 16:58 UTC
